""" Script generated by pyDatView - The script will likely need to be adapted. """
import sys
print(sys.executable)

import matplotlib.pyplot as plt
import numpy as np
import openfast_toolbox
import os
scriptDir = os.path.dirname(__file__)
print(__file__)
print(openfast_toolbox.__file__)
from openfast_toolbox.io.fast_linearization_file import FASTLinearizationFile

# --- Script parameters
filename = 'ws03.0.1.lin'

# --- Open and convert files to DataFrames
lin = FASTLinearizationFile(filename)
print(lin)
print(lin['A'])
print(lin['A'].shape)
print('Using to dataframe:')
dfs = lin.toDataFrame()
print(dfs.keys())
print('A:')
print(dfs['A'])


import pdb; pdb.set_trace()